'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TutorSignUp
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''fnametxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fnametxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mnametxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnametxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnametxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnametxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dobtxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dobtxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''maleradio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maleradio As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
    
    '''<summary>
    '''femaleradio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents femaleradio As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
    
    '''<summary>
    '''unametxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents unametxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pwordtxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pwordtxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''emailtxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailtxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''contacttxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contacttxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''submitbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitbtn As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
